name: Deploy AKS TemplateSpec

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
    paths:
      - templates/aks/**
  workflow_dispatch:

env:
  templateSpec: "aks"
  templateSpecVersion: "0.0.1"

defaults:
  run:
    shell: bash
    working-directory: "templates/$templateSpec/"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure (Hotmail)
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_HOTMAIL_TEMPLATESPECS}}
          enable-AzPSSession: false

      # Runs a single command using the runners shell
      - name: "deploy $templateSpec templatespec"
        run: az ts create --name "$templateSpec" --resource-group templateSpecs --location westeurope --template-file ./azuredeploy.json --version "$templateSpecVersion"

      - name: Azure (Microsoft)
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_MSFT_TEMPLATESPECS}}
          enable-AzPSSession: false

      # Runs a single command using the runners shell
      - name: "deploy $templateSpec templatespec"
        run: az ts create --name "$templateSpec" --resource-group templateSpecs --location westeurope --template-file ./azuredeploy.json --version "$templateSpecVersion"

      - name: Azure (Live)
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_LIVE_TEMPLATESPECS}}
          enable-AzPSSession: false

      # Runs a single command using the runners shell
      - name: "deploy $templateSpec templatespec"
        run: az ts create --name "$templateSpec" --resource-group templateSpecs --location westeurope --template-file ./azuredeploy.json --version "$templateSpecVersion"